# Generated by Django 4.0.4 on 2022-12-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Users Group'},
        ),
        migrations.AddField(
            model_name='group',
            name='max_rows',
            field=models.IntegerField(default=10),
        ),
    ]
