# Generated by Django 4.0.4 on 2022-12-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_group_max_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_rows',
            field=models.IntegerField(),
        ),
    ]
