# Generated by Django 4.0.4 on 2022-12-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_group_is_active_group_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
