# Generated by Django 4.0.4 on 2022-12-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_bread_quantity_group_lambs_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='bread_quantity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lambs_quantity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pigs_quantity',
        ),
    ]
