# Generated by Django 4.0.4 on 2022-12-28 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='address',
        ),
        migrations.AddField(
            model_name='row',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
