# Generated by Django 4.0.4 on 2022-12-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0003_row_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='bread_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='lambs_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='pigs_quantity',
            field=models.FloatField(default=0),
        ),
    ]
