# Generated by Django 4.0.4 on 2022-12-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0004_row_bread_quantity_row_lambs_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='bread_quantity',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='row',
            name='lambs_quantity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='row',
            name='pigs_quantity',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
